<a href="https://colab.research.google.com/github/biancabuleu/car-plate-detect/blob/main/dizertatie_carPlate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ln -s "/content/drive/MyDrive/CarPlate" "/content/CarPlate"

In [ ]:
import pandas as pd
import xml.etree.ElementTree as xet


In [ ]:
from glob import glob

In [ ]:
path = glob('/content/drive/MyDrive/CarPlate/images/*.xml')
path

['/content/drive/MyDrive/CarPlate/images/N2.xml',
 '/content/drive/MyDrive/CarPlate/images/N3.xml',
 '/content/drive/MyDrive/CarPlate/images/N4.xml',
 '/content/drive/MyDrive/CarPlate/images/N5.xml',
 '/content/drive/MyDrive/CarPlate/images/N6.xml',
 '/content/drive/MyDrive/CarPlate/images/N7.xml',
 '/content/drive/MyDrive/CarPlate/images/N8.xml',
 '/content/drive/MyDrive/CarPlate/images/N9.xml',
 '/content/drive/MyDrive/CarPlate/images/N11.xml',
 '/content/drive/MyDrive/CarPlate/images/N12.xml',
 '/content/drive/MyDrive/CarPlate/images/N14.xml',
 '/content/drive/MyDrive/CarPlate/images/N15.xml',
 '/content/drive/MyDrive/CarPlate/images/N16.xml',
 '/content/drive/MyDrive/CarPlate/images/N17.xml',
 '/content/drive/MyDrive/CarPlate/images/N18.xml',
 '/content/drive/MyDrive/CarPlate/images/N19.xml',
 '/content/drive/MyDrive/CarPlate/images/N20.xml',
 '/content/drive/MyDrive/CarPlate/images/N21.xml',
 '/content/drive/MyDrive/CarPlate/images/N22.xml',
 '/content/drive/MyDrive/CarPlate/image

In [ ]:
labels_dict = dict(filepath=[],xmin=[],xmax=[],ymin=[],ymax=[])
for filename in path:

    #filename = path[0]
    info = xet.parse(filename)
    root = info.getroot()
    member_object = root.find('object')
    labels_info = member_object.find('bndbox')
    xmin = int(labels_info.find('xmin').text)
    xmax = int(labels_info.find('xmax').text)
    ymin = int(labels_info.find('ymin').text)
    ymax = int(labels_info.find('ymax').text)
    #print(xmin,xmax,ymin,ymax)
    labels_dict['filepath'].append(filename)
    labels_dict['xmin'].append(xmin)
    labels_dict['xmax'].append(xmax)
    labels_dict['ymin'].append(ymin)
    labels_dict['ymax'].append(ymax)

In [ ]:
df = pd.DataFrame(labels_dict)
df

filepath  xmin  xmax  ymin  ymax
0      /content/drive/MyDrive/CarPlate/images/N2.xml  1804  2493  1734  1882
1      /content/drive/MyDrive/CarPlate/images/N3.xml    73   260   381   462
2      /content/drive/MyDrive/CarPlate/images/N4.xml  1326  1830  1464  1607
3      /content/drive/MyDrive/CarPlate/images/N5.xml   938  1173   709   762
4      /content/drive/MyDrive/CarPlate/images/N6.xml   858  1122   611   676
..                                               ...   ...   ...   ...   ...
477  /content/drive/MyDrive/CarPlate/images/N504.xml   666   793   404   445
478  /content/drive/MyDrive/CarPlate/images/N503.xml  1017  1104   369   397
479  /content/drive/MyDrive/CarPlate/images/N502.xml   552   625   387   416
480  /content/drive/MyDrive/CarPlate/images/N501.xml   665   883   606   661
481  /content/drive/MyDrive/CarPlate/images/N500.xml   252   428   490   533

[482 rows x 5 columns]

In [ ]:
df.to_csv('/content/CarPlate/labels.csv',index=False)

In [ ]:
import os

# Define the folder path
folder_path = "/content/CarPlate/images"

# Get a list of all image files in the folder
image_files = [file for file in os.listdir(folder_path) if file.endswith(".jpg") or file.endswith(".jpeg") or file.endswith(".png")]

# Check if each image file has a corresponding XML file
missing_xml_files = []
for image_file in image_files:
    # Remove extension to get the base file name
    base_name, _ = os.path.splitext(image_file)
    xml_file = base_name + ".xml"
    # Check if XML file exists
    if xml_file not in os.listdir(folder_path):
        missing_xml_files.append(xml_file)

# Print the missing XML files
if missing_xml_files:
    print("The following XML files are missing:")
    for xml_file in missing_xml_files:
        print(xml_file)
else:
    print("All image files have corresponding XML files.")


All image files have corresponding XML files.


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2

In [ ]:
df = pd.read_csv('/content/CarPlate/labels.csv')
df.head()

filepath  xmin  xmax  ymin  ymax
0  /content/drive/MyDrive/CarPlate/images/N2.xml  1804  2493  1734  1882
1  /content/drive/MyDrive/CarPlate/images/N3.xml    73   260   381   462
2  /content/drive/MyDrive/CarPlate/images/N4.xml  1326  1830  1464  1607
3  /content/drive/MyDrive/CarPlate/images/N5.xml   938  1173   709   762
4  /content/drive/MyDrive/CarPlate/images/N6.xml   858  1122   611   676

In [ ]:
import xml.etree.ElementTree as xet

In [ ]:
filename = df['filepath'][0]
filename

'/content/drive/MyDrive/CarPlate/images/N2.xml'

In [ ]:
def getFileName(filename):
    filename_image = xet.parse(filename).getroot().find('filename').text
    filepath_image = os.path.join('./images',filename_image)
    return filepath_image

In [ ]:
getFileName(filename)

'./images/N2.jpeg'

In [ ]:
image_path = list(df['filepath'].apply(getFileName))
image_path

['./images/N2.jpeg',
 './images/N3.jpeg',
 './images/N4.jpeg',
 './images/N5.jpeg',
 './images/N6.jpeg',
 './images/N7.jpeg',
 './images/N8.jpeg',
 './images/N9.jpeg',
 './images/N11.jpeg',
 './images/N12.jpeg',
 './images/N14.jpeg',
 './images/N15.jpeg',
 './images/N16.jpeg',
 './images/N17.jpeg',
 './images/N18.jpeg',
 './images/N19.jpeg',
 './images/N20.jpeg',
 './images/N21.jpeg',
 './images/N22.jpeg',
 './images/N23.jpeg',
 './images/N24.jpeg',
 './images/N25.jpeg',
 './images/N27.jpeg',
 './images/N28.jpeg',
 './images/N30.jpeg',
 './images/N31.jpeg',
 './images/N32.jpeg',
 './images/N33.jpeg',
 './images/N34.jpeg',
 './images/N35.jpeg',
 './images/N36.jpeg',
 './images/N37.jpeg',
 './images/N38.jpeg',
 './images/N40.jpeg',
 './images/N42.jpeg',
 './images/N43.jpeg',
 './images/N44.jpeg',
 './images/N45.jpeg',
 './images/N46.jpeg',
 './images/N47.jpeg',
 './images/N48.jpeg',
 './images/N49.jpeg',
 './images/N50.jpeg',
 './images/N51.jpeg',
 './images/N52.jpeg',
 './images/N53.jpe

In [ ]:
file_path = image_path[0]
file_path

'./images/N2.jpeg'

In [ ]:
img = cv2.imread("/content/CarPlate/"+file_path)
#<xmin>1804</xmin>
#<ymin>1734</ymin>
#<xmax>2493</xmax>
#<ymax>1882</ymax>


In [ ]:
cv2.rectangle(img,(1804,2493),(1734,1882),(0,255,0),3)

array([[[ 61,  83,  95],
        [ 60,  82,  94],
        [ 62,  84,  96],
        ...,
        [184, 115,  35],
        [183, 114,  34],
        [183, 114,  34]],

       [[ 64,  86,  98],
        [ 61,  83,  95],
        [ 61,  83,  95],
        ...,
        [185, 116,  36],
        [183, 114,  34],
        [183, 114,  34]],

       [[ 66,  87, 102],
        [ 64,  85, 100],
        [ 62,  83,  98],
        ...,
        [183, 117,  36],
        [181, 112,  32],
        [180, 111,  31]],

       ...,

       [[ 75,  90,  93],
        [ 70,  85,  88],
        [ 67,  79,  83],
        ...,
        [ 80,  97, 110],
        [ 74,  90, 103],
        [ 70,  86,  99]],

       [[ 83,  97, 103],
        [ 66,  80,  86],
        [ 49,  61,  65],
        ...,
        [ 95, 112, 125],
        [ 90, 106, 119],
        [ 86,  99, 113]],

       [[ 96, 110, 116],
        [ 72,  86,  92],
        [ 49,  60,  64],
        ...,
        [105, 122, 135],
        [103, 116, 130],
        [ 96, 109, 123]]

In [ ]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import load_img, img_to_array

In [ ]:
labels = df.iloc[:,1:].values

In [ ]:
data =[]
output = []

for ind in range(len(image_path)):
    image = image_path[ind]

    img_arr = cv2.imread("/content/CarPlate/" +image)
    print(img_arr)
    h,w,d = img_arr.shape

    ##preprocesare
    load_image = load_img("/content/CarPlate/" +image, target_size=(224,224))
    load_image_arr = img_to_array(load_image)
    norm_load_image_arr = load_image_arr/225.0 #normalizare

    xmin,xmax,ymin,ymax = labels[ind]
    nxmin,nxmax = xmin/w, xmax/w
    nymin, nymax = ymin/h, ymax/h
    label_norm = (nxmin,nxmax,nymin,nymax) #normalizare output
    data.append(norm_load_image_arr)
    output.append(label_norm)

Datele de ieșire de afișat au fost trunchiate la ultimele 5000 linii.
  [ 0  0  3]
  [ 0  0  3]]]
[[[ 93 104 162]
  [ 93 102 161]
  [ 95 102 161]
  ...
  [ 81  83 134]
  [ 81  83 134]
  [ 81  83 134]]

 [[ 93 104 162]
  [ 94 103 162]
  [ 94 101 160]
  ...
  [ 81  83 134]
  [ 81  83 134]
  [ 81  83 134]]

 [[ 94 103 162]
  [ 94 102 161]
  [ 94 101 160]
  ...
  [ 81  83 134]
  [ 81  83 134]
  [ 81  83 134]]

 ...

 [[ 22  27  71]
  [ 22  27  71]
  [ 22  27  71]
  ...
  [ 12  17  52]
  [ 12  17  52]
  [ 12  17  52]]

 [[ 22  27  71]
  [ 22  27  71]
  [ 22  27  71]
  ...
  [ 12  17  52]
  [ 12  17  52]
  [ 12  17  52]]

 [[ 22  27  71]
  [ 22  27  71]
  [ 22  27  71]
  ...
  [ 12  17  52]
  [ 12  17  52]
  [ 12  17  52]]]
[[[185 169 193]
  [191 175 199]
  [191 173 198]
  ...
  [220 218 255]
  [223 220 255]
  [227 225 255]]

 [[185 169 193]
  [188 171 196]
  [189 171 196]
  ...
  [224 222 255]
  [224 221 255]
  [225 222 255]]

 [[183 167 191]
  [187 170 195]
  [188 169 195]
  ...
  [226 224

In [ ]:
X = np.array(data,dtype=np.float32)
y= np.array(output,dtype=np.float32)

In [ ]:
X.shape,y.shape

((482, 224, 224, 3), (482, 4))

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((385, 224, 224, 3), (97, 224, 224, 3), (385, 4), (97, 4))

In [ ]:
from tensorflow.keras.applications import MobileNetV2, InceptionV3, InceptionResNetV2
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input
from tensorflow.keras.models import Model
import tensorflow as tf

In [ ]:
inception_resnet = InceptionResNetV2(weights="imagenet",include_top=False,input_tensor=Input(shape=(224,224,3)))
inception_resnet.trainable = False

headmodel = inception_resnet.output
headmodel = Flatten()(headmodel)
headmodel=Dense(500,activation="relu")(headmodel)
headmodel=Dense(250,activation="relu")(headmodel)
headmodel=Dense(4,activation="sigmoid")(headmodel)

#model

model = Model(inputs=inception_resnet.input,outputs = headmodel)

219055592/219055592 [==============================] - 1s 0us/step


In [ ]:
#compilare model
model.compile(loss="mse",optimizer =tf.keras.optimizers.Adam(learning_rate =1e-4))
model.summary()

In [ ]:
from tensorflow.keras.callbacks import TensorBoard
tfb = TensorBoard('object_detection')

In [ ]:
history = model.fit(x=x_train,y=y_train,batch_size=32,epochs=700,
                    validation_data=(x_test,y_test),callbacks=[tfb])

Epoch 1/700
13/13 [==============================] - 144s 11s/step - loss: 0.1665 - val_loss: 0.1626
Epoch 2/700
13/13 [==============================] - 138s 11s/step - loss: 0.1539 - val_loss: 0.1578
Epoch 3/700
13/13 [==============================] - 138s 11s/step - loss: 0.1535 - val_loss: 0.1547
Epoch 4/700
13/13 [==============================] - 138s 11s/step - loss: 0.1499 - val_loss: 0.1606
Epoch 5/700
13/13 [==============================] - 149s 12s/step - loss: 0.1617 - val_loss: 0.1631
Epoch 6/700
13/13 [==============================] - 147s 11s/step - loss: 0.1528 - val_loss: 0.1517
Epoch 7/700
13/13 [==============================] - 142s 11s/step - loss: 0.1433 - val_loss: 0.1469
Epoch 8/700
13/13 [==============================] - 128s 10s/step - loss: 0.1431 - val_loss: 0.1414
Epoch 9/700
13/13 [==============================] - 122s 9s/step - loss: 0.1360 - val_loss: 0.1388
Epoch 10/700
13/13 [==============================] - 124s 10s/step - loss: 0.1329 - val_los

KeyboardInterrupt: 

In [ ]:
model.save('/content/CarPlate/models/object_detection.keras')

In [ ]:
pd.DataFrame(history.history).plot(kind='line')

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array

In [ ]:
# load model
model = tf.keras.models.load_model('/content/CarPlate/models/object_detection.keras')
print('model loaded sucessfully')

In [ ]:
path = '/content/CarPlate/test_images/MY.jpeg'
image = load_img(path) # PIL object
image = np.array(image,dtype=np.uint8) # 8 bit array (0,255)
image1 = load_img(path,target_size=(224,224))
image_arr_224 = img_to_array(image1)/255.0  # convert into array and get the normalized output

In [ ]:
# size of the orginal image
h,w,d = image.shape
print('Height of the image =',h)
print('Width of the image =',w)

In [ ]:
plt.figure(figsize=(10,8))
plt.imshow(image)
plt.show()

In [ ]:
image_arr_224.shape

In [ ]:
test_arr = image_arr_224.reshape(1,224,224,3)
test_arr.shape

In [ ]:
# make predictions
coords = model.predict(test_arr)
coords

In [ ]:
# denormalize the values
denorm = np.array([w,w,h,h])
coords = coords * denorm
coords

In [ ]:
coords = coords.astype(np.int32)
coords

In [ ]:
# draw bounding on top the image
xmin, xmax,ymin,ymax = coords[0]
pt1 =(xmin,ymin)
pt2 =(xmax,ymax)
print(pt1, pt2)
cv2.rectangle(image,pt1,pt2,(0,255,0),3)

plt.figure(figsize=(10,8))
plt.imshow(image)
plt.show()